Modifying openmetadata compose

diff --git a/openmetadata/docker-compose.yml b/openmetadata/docker-compose.yml
--- a/openmetadata/docker-compose.yml
+++ b/openmetadata/docker-compose.yml
@@ -510,13 +510,19 @@ services:
       - "-c"
       - |
         mkdir -p /opt/airflow/dags/dbt_project;
-        chmod -R 777 /opt/airflow/dags/dbt_project;
-        if [ ! -d "/opt/airflow/dags/dbt_project/.git" ]; then
-          git clone --depth 1 --single-branch --branch main https://github.com/NawalHamed/mem-dwh.git /tmp/mem-dwh;
-          cp -r /tmp/mem-dwh/dbt/mem_dwh /opt/airflow/dags/dbt_project;
-          rm -rf /tmp/mem-dwh;
+        if [ -w "/opt/airflow/dags/dbt_project" ]; then
+          echo "Setting up dbt_project directory...";
+          chmod -R 775 /opt/airflow/dags/dbt_project || echo "Cannot change permissions, skipping...";
+        
+          if [ ! -d "/opt/airflow/dags/dbt_project/.git" ]; then
+            git clone --depth 1 --single-branch --branch main https://github.com/NawalHamed/mem-dwh.git /tmp/mem-dwh;
+            cp -r /tmp/mem-dwh/dbt/mem_dwh /opt/airflow/dags/dbt_project || echo "Copy failed, check permissions.";
+            rm -rf /tmp/mem-dwh;
+          else
+            git -C /opt/airflow/dags/dbt_project pull;
+          fi
         else
-          git -C /opt/airflow/dags/dbt_project pull;
+          echo "Directory not writable. Check permissions.";
         fi
         /opt/airflow/ingestion_dependency.sh
 
@@ -529,7 +535,7 @@ services:
       - ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
       - ingestion-volume-dags:/opt/airflow/dags
       - ingestion-volume-tmp:/tmp
-      - dbt-project-data:/opt/airflow/dags/dbt_project
+      - dbt-project-data:/opt/airflow/dags/dbt_project:rw
     healthcheck:
       test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
       interval: 15s
